baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hung-Yi’s Journal"
theme = "ink"
paginate = 5

copyright = "© Copyright"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "paraiso-dark"
    tabWidth = 2

# googleAnalytics = "UA-123-45"
# disqusShortname = "ink-demo"

[params]
    subtitle = "Front-end&nbsp;Developer, Emacs&nbsp;Adventurer, Home&nbsp;Cook"

    # Optional 64x64 avatar image.
    avatar = "/HY_Light_and_Color_2.svg"

    # Content types to disable Disqus on.
    disableDisqusTypes = ["page"]

    featherIconsCDN = true

    mode = "auto" # "dark" or "auto"
    # customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    # customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
    # customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

# [[params.social]]
# name = "Github"
# icon = "github"
# url = "https://github.com/knadh/hugo-ink"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
