;;; base-template.el --- blog base template -*- lexical-binding: t; -*-
;;
;;; Commentary:
;;  blog base template
;;
;;; Code:

(require 'charge)

(defun my/blog/render-base (site main &optional subtitle meta)
  "Renders base template with SITE, MAIN content, SUBTITLE and META tags."
  (let ((site-name (plist-get site :name))
        (base-url (plist-get site :base-url)))
    (charge-html
     "<!DOCTYPE html>"
     `(html
       :lang "en"
       (head
        (meta :charset "utf-8")
        (title ,(when subtitle (concat subtitle " – ")) ,site-name)
        (meta :name "viewport" :content "width=device-width, initial-scale=1")
        (link :rel "stylesheet" :type "text/css" :href ,(concat base-url "style.css"))
        (link :rel "preconnect" :href "https://fonts.googleapis.com")
        (link :rel "preconnect" :href "https://fonts.gstatic.com" :crossorigin nil)
        (link :rel "stylesheet" :href "https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;0,1000;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900;1,1000&display=swap")
        (link :rel "stylesheet" :href "https://fonts.googleapis.com/css2?family=Sen:wght@400;700;800&display=swap")
        (link :rel "stylesheet" :href "https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap")
        (link :rel "icon" :href ,(concat base-url "favicon.ico") :type "image/x-icon")
        ,meta)
       (body
        (input :id "inverter" :type "checkbox")
        (div
         :id "theme-container"
         (header
          (div
           (h1
            (a
             :href ,base-url
             (img :src ,(concat base-url "HY_Light_and_Color_2.svg") :alt "Hung-Yi's Logo")
             (span :class "header-title-text" ,site-name)))
           (a :href "#main" :class "hidden" "Jump to main content")
           (nav
            (ul
             :class "menu"
             (li (a :href ,base-url "BLOG"))
             (li (a :href ,(concat base-url "about") "ABOUT ME")))
            (label :id "sun" :for "inverter" (svg :viewBox "0 0 24 24" (use :href ,(concat base-url "sun.svg#icon"))))
            (label :id "moon" :for "inverter" (svg :viewBox "0 0 24 24" (use :href ,(concat base-url "moon.svg#icon"))))
            ;; inline script to set the theme inverter checkbox ASAP, to prevent flicker
            (script "document.querySelector('#inverter').checked = localStorage.getItem('themeInverted') === 'true'"))))
         (main
          :id "main"
          (div ,main))
         (svg
          :class "footer-swoosh" :fill "transparent" :viewBox "0 0 100 5"
          (path :d "M 0 3 C 11 3 22 0 33 0 C 44 0 55 3 66 3 C 77 3 88 0 100 0 L 100 5 L 0 5 Z"))
         (footer
          (div
           """
         All prose, stylesheets and snippets of code
         (and even most graphics!) on this site
         are written or generated by hand using
         """
           (a :href "https://www.gnu.org/software/emacs/" "GNU Emacs")
           " running on "
           (a :href "https://github.com/hlissner/doom-emacs" "Doom Emacs"))))
        (script :src ,(concat base-url "script.js?1"))
        ;; (script :async nil :src "https://www.googletagmanager.com/gtag/js?id=UA-180663322-1")
        )))))

(provide 'base-template)
;;; base-template.el ends here
