#+TITLE: I Choose JetBrains Mono
#+DRAFT: true
When it comes to programming fonts[fn:1], we've seen a recent explosion of innovation—especially when it comes to using (or abusing) ligatures for code clarity. A discerning programmer in 2020 will have several choices that all claim to be amazing. To help with that, today I'll outline the ones that I've come across in my travels and reveal why I chose [[https://www.jetbrains.com/lp/mono/][JetBrains Mono]] in the end.

[fn:1] In common parlance, the word 'font' is used to refer to both /typefaces/ or /fonts/ and no distinction is made between the two. Although they are technically different, I'm no typographer, so I'm sticking to the colloquial usage.


# more

* Ligatures?

First, a quick primer on ligatures and their use in code. In plain English, a ligature is when a *special combination of one or more characters is joined together to form a new symbol*. Look closely at the combination of the letters 'f' and 'i' below.

#+begin_quote
Let's fight fire with fire.
#+end_quote

Because the dot of the 'i' normally collides with the hook of the 'f', most good fonts will combine them such that the dot is "removed". It just looks neater that way.

Programming ligatures take this to the extreme with special symbols. The most apparent example to me is the arrow operator that is often used for lambda functions: ~=>~. Most fonts with programming ligatures will combine it into an actual arrow similar to this: ⇒.

Other common programming ligatures include:
- ~>=~ into ≥
- ~<=~ into ≤
- ~!=~ into ≠
- ~|>~ into ▷
- and many more...

It's a matter of personal taste, but many programmers—myself included—find that these ligatures make code look more meaningful and easier to parse.

Now, on to some actual programming fonts...

* Hasklig

Going as far back as 2012, [[https://github.com/i-tu/Hasklig][Hasklig]] was one of the earlier programming fonts to use ligatures for code. It uses the beautiful [[https://github.com/adobe-fonts/source-code-pro][Source Code Pro]] as its base font with ligatures mainly geared towards code written in Haskell.

Sadly, this means that it does not support that many ligatures for general programming. It also hasn't received any major updates for a long time now. For those reasons, I never considered Hasklig suitable for me, even though I honestly did like Source Code Pro as a whole.

* Fira Code

[[https://github.com/tonsky/FiraCode][Fira Code]] was the first experience I had with programming ligatures. I used it for more than 4 years and I still consider it a very solid choice today. It's based on the monospaced variant of Mozilla's [[http://mozilla.github.io/Fira/][Fira]] type family, [[https://fonts.google.com/specimen/Fira+Mono][Fira Mono]].

I was happy until I discovered that Fira Mono didn't have a dedicated italic variant. This deficiency was carried over into Fira Code, making it difficult for me to show true italics in Emacs, especially when using [[https://orgmode.org/][Org mode]]. So, after 4+ years of loyalty, I decided to go searching for a new programming font.

* Cascadia Code

* Iosevka

* JetBrains Mono
